name: nlp_ema
channels:
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - scipy
  - statsmodels
  - pip:
    - transformers
    - sentence-transformers
    - vaderSentiment
